apiVersion: apps/v1  # Указывает на версию API Kubernetes, используемую для создания объекта Deployment. Для деплоев используется "apps/v1".
kind: Deployment  # Определяет тип объекта, который вы создаете. В данном случае это Deployment.
metadata:
  name: lite-deployment  # Уникальное имя для этого деплоя в рамках текущего namespace. Имя должно быть DNS-совместимым.
  labels:  # Набор меток для организации и поиска объектов. 
    app: lite-app  # Произвольная метка. Используется для идентификации и группировки объектов.
spec:
  replicas: 1  # Количество реплик (подов), которые будут запущены. В данном случае создаются 3 реплики.
  selector:  # используется для для поиска одноименных подов
    matchLabels:
      app: lite-app  # Метки, по которым будут выбраны поды для этого деплоя. Эти метки должны совпадать с метками подов.
  template:  # шаблон для подов
    metadata:
      labels:
        app: lite-app  # Метки, применяемые к подам, созданным этим деплоем. Эти метки должны совпадать с метками в селекторе.
    spec:
      containers:
      - name: lite-container  # Уникальное имя для этого контейнера в рамках пода.
        image: nginx:latest  # Docker-образ, используемый для создания контейнера. "nginx:latest" указывает на образ Nginx последней версии.
        ports:
        - containerPort: 80  # Порт внутри контейнера, который будет открыт и прослушиваться. В данном случае, это порт 80.
        volumeMounts:
        - name: lite-content
          mountPath: /usr/share/nginx/html  # Стандартный путь для NGINX
      volumes:
      - name: lite-content
        configMap:
          name: lite-app-content 