apiVersion: networking.k8s.io/v1  # Версия API Kubernetes, используемая для создания Ingress-объекта. Актуальная версия для большинства Kubernetes-кластеров.
kind: Ingress                     # Тип ресурса Kubernetes, указывающий, что создается объект Ingress для маршрутизации трафика.
metadata:
  name: nginx-ingress             # Название объекта Ingress. Используется для идентификации этого ресурса в неймспейсе.
  #namespace: lite-site             # Неймспейс, в котором будет размещен объект Ingress. Должен совпадать с неймспейсом других объектов, таких как Service.
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Аннотация для NGINX Ingress-контроллера. Указывает на то, что путь запроса должен быть переписан на корневой (/) для корректного маршрутизации.

spec:
  rules:                          # Секция правил маршрутизации. Определяет, как Ingress должен обрабатывать входящие запросы на основе домена и пути.
  - host: lite-site.com             # Доменное имя, по которому Ingress будет принимать HTTP-запросы. Здесь это "example.com".
    http:
      paths:                      # Список путей, определяющих, как маршрутизировать запросы на основе URL-пути.
      - path: /                   # Указывает путь для маршрутизации. Здесь "/" означает, что все запросы на "example.com/" будут направлены на указанный сервис.
        pathType: Prefix          # Тип пути, определяющий, как трактуется "path". "Prefix" означает, что все запросы, начинающиеся с "/", будут перенаправлены.
        backend:                  # Определение бэкенда, на который будут направляться запросы. Здесь указывается сервис и порт для направления трафика.
          service:
            name: nginx-service   # Имя сервиса, к которому будет направляться трафик. Сервис должен существовать в том же неймспейсе.
            port:
              number: 80          # Номер порта, на который будет направлен запрос. Здесь это порт 80, где ожидается NGINX для обработки HTTP-запросов.
