---
- hosts: master
  become: yes
  tasks:

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Get the Ubuntu codename
      command: lsb_release -cs
      register: ubuntu_codename

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-{{ ubuntu_codename.stdout }} main"
        state: present
        filename: kubernetes.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kubernetes binaries
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold versions of packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
