---
- name: Установка Docker
  hosts: all
  become: true
  
  tasks:
    - name: Обновить все системные пакеты
      apt:
        update_cache: yes
        
    - name: Установка необходимых зависимостей
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Добавление GPG ключа Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление репозитория Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Обновление кэша пакетов
      apt:
        update_cache: yes

    - name: Установка Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Docker запущен и включен при загрузке
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Добавление пользователя ubuntu в группу Docker
      user:
        name: ubuntu
        group: docker

    - name: Установка git
      apt:
        name: git
        state: present